{% set name = "timezonefinder" %}
{% set version = "4.1.0" %}
{% set sha256 = "0569558a0343e5c0ff6a6d92dc30725ddedec13b6b57fa642c70121dd33496a3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python >3
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python >3
    - setuptools
  run:
    - python >3
    - importlib_resources
    - numpy
    - numba

test:
  imports:
    - timezonefinder
    - timezonefinder.timezonefinder
    - timezonefinder.helpers

about:
  home: https://github.com/MrMinimal64/timezonefinder
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'fast python package for finding the timezone of any point on earth (coordinates) offline'
  description: |
    This is a fast and lightweight python package for looking up the corresponding timezone for given 
    coordinates on earth entirely offline.

  dev_url: https://github.com/MrMinimal64/timezonefinder

extra:
  recipe-maintainers:
    - snowman2
